name: Cache Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-7680cda
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-7680cda

      - name: Check cache result
        run: echo "Cache hit? -> ${{ steps.cache-step.outputs.cache-hit }}"
